EdgarAguasvivasPrueba/Models/ErrorViewModel.cs
using System;

namespace EdgarAguasvivasPrueba.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EdgarAguasvivasPrueba/Models/Estado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EdgarAguasvivasPrueba.Models
{
    public class Estado
    {
        public int Id { get; set; }

        public string EstadoNombre { get; set; }

        public ICollection<Solicitud> Solicitud { get; set; }
    }
}

EdgarAguasvivasPrueba/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EdgarAguasvivasPrueba.Models
{
    public class Persona
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string Pasaporte { get; set; }
        public string Direccion { get; set; }
        public string Sexo { get; set; }

        public  ICollection<Solicitud> Solicitud { get; set; }
    }
}

EdgarAguasvivasPrueba/Models/Solicitud.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EdgarAguasvivasPrueba.Models
{
    public class Solicitud
    {
        public int Id { get; set; }
        public DateTime FechaCreacion { get; set; }

        public int PersonaId { get; set; }
        public  Persona Persona { get; set; }

        public int EstadoId { get; set; }
        public  Estado Estado { get; set; }
    }
}

EdgarAguasvivasPrueba/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EdgarAguasvivasPrueba.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EdgarAguasvivasPrueba/Controllers/PersonaController.cs
using EdgarAguasvivasPrueba.Data;
using EdgarAguasvivasPrueba.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EdgarAguasvivasPrueba.Controllers
{
    public class PersonaController : Controller
    {
        private DataContext _data;

        public PersonaController(DataContext datacontext)
        {
            _data = datacontext;
        }
        public IActionResult IndexPersonas()
        {
            return View(_data.Personas.ToList());
        }

        public IActionResult CreatePersona()
        {
            ViewBag.Estados = new SelectList(_data.Estados, "Id", "EstadoNombre");
            ViewBag.Personas = new SelectList(_data.Personas, "Id", "Nombre");
            return View();
        }

        [HttpPost]
        public IActionResult CreatePersona(Persona personaModel)
        {
            _data.Personas.Add(personaModel);
            _data.SaveChanges();

            return RedirectToAction("IndexPersonas");
        }


        public IActionResult EditPersona(int? Id)
        {
            return View(_data.Personas.Where(e => e.Id == Id).FirstOrDefault());
        }

        [HttpPost]
        public IActionResult EditPersona(Persona personaModel)
        {
            _data.Personas.Update(personaModel);
            _data.SaveChanges();

            return RedirectToAction("IndexPersonas");
        }

        [HttpPost]
        public IActionResult DeletePersona(int id)
        {
            var persona = _data.Personas.Where(a => a.Id == id).FirstOrDefault();
            _data.Personas.Remove(persona);
            _data.SaveChanges();
            return RedirectToAction("IndexPersonas");
        }
    }
}

EdgarAguasvivasPrueba/Controllers/SolicitudesController.cs
using EdgarAguasvivasPrueba.Data;
using EdgarAguasvivasPrueba.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EdgarAguasvivasPrueba.Controllers
{
    public class SolicitudesController : Controller
    {
        private DataContext _data;

        public SolicitudesController(DataContext datacontext)
        {
            _data = datacontext;
        }

        public IActionResult IndexSolicitudes(int estado = 0)
        {
            ViewBag.Estados = new SelectList(_data.Estados, "Id", "EstadoNombre");
            if (estado != 0) 
            {
                var query = _data.Solicitudes.Include(e => e.Persona).Include(e => e.Estado).Where(e => e.EstadoId == estado).ToList();              
                return View(query);
            }
            else
            {
            var query = _data.Solicitudes.Include(e => e.Persona).Include(e => e.Estado).ToList();
                return View(query);
            }
          
            
           
        }

      

        public IActionResult CreateSolicitud()
        {
            ViewBag.Estados = new SelectList(_data.Estados, "Id", "EstadoNombre");
            ViewBag.Personas = new SelectList( _data.Personas,"Id","Nombre");
            return View();
        }

        [HttpPost]
        public IActionResult CreateSolicitud(Solicitud solicitudModel)
        {
            _data.Solicitudes.Add(solicitudModel);
            _data.SaveChanges();

            return RedirectToAction("IndexSolicitudes");
        }


        public IActionResult EditSolicitud(int? Id)
        {
            ViewBag.Estados = new SelectList(_data.Estados, "Id", "EstadoNombre");
            ViewBag.Personas = new SelectList(_data.Personas, "Id", "Nombre");
            return View(_data.Solicitudes.Where(e => e.Id == Id).FirstOrDefault());
        } 
        
        [HttpPost]
        public IActionResult EditSolicitud(Solicitud solicitudModel)
        {
            _data.Solicitudes.Update(solicitudModel);
            _data.SaveChanges();

            return RedirectToAction("IndexSolicitudes");
        }

        [HttpPost]
        public IActionResult DeleteSolicitud(int id)
        {
            var solicitud = _data.Solicitudes.Where(a => a.Id == id).FirstOrDefault();
            _data.Solicitudes.Remove(solicitud);
            _data.SaveChanges();
            return RedirectToAction("IndexSolicitudes");
        }

        public JsonResult filterSolicitudes(int estado)
        {
            var query = _data.Solicitudes.Include(e => e.Persona).Include(e => e.Estado).Where(e => e.EstadoId == estado).ToList();


            return Json(query);
        }
    }
}

EdgarAguasvivasPrueba/Views/Persona/CreatePersona.cshtml
@model Persona

@{
    Layout = "_Layout";
}

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<form class="m-1 p-1" method="post">
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" type="text" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Apellido"></label>
        <input asp-for="Apellido" type="text" class="form-control" />
        <span asp-validation-for="Apellido" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FechaNacimiento"></label>
        <input asp-for="FechaNacimiento" type="date" class="form-control" />
        <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Pasaporte"></label>
        <input asp-for="Pasaporte" type="text" class="form-control" />
        <span asp-validation-for="Pasaporte" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Direccion"></label>
        <textarea asp-for="Direccion" class="form-control"></textarea>
        <span asp-validation-for="Direccion" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Sexo"></label>
        <select asp-for="Sexo" class="form-control">
            <option value="0" disabled selected>Seleccione</option>
            <option value="Masculino">Masculino</option>
            <option value="Femenino">Femenino</option>
        </select>
        <span asp-validation-for="Apellido" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Guardar</button>
</form>  

EdgarAguasvivasPrueba/Views/Persona/EditPersona.cshtml
@model Persona

@{
    Layout = "_Layout";
}

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<form class="m-1 p-1" method="post">
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" type="text" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Apellido"></label>
        <input asp-for="Apellido" type="text" class="form-control" />
        <span asp-validation-for="Apellido" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FechaNacimiento"></label>
        <input asp-for="FechaNacimiento" type="date" class="form-control" />
        <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Pasaporte"></label>
        <input asp-for="Pasaporte" type="text" class="form-control" />
        <span asp-validation-for="Pasaporte" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Direccion"></label>
        <textarea asp-for="Direccion" class="form-control"></textarea>
        <span asp-validation-for="Direccion" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Sexo"></label>
        <select asp-for="Sexo" class="form-control">
            <option value="0" disabled selected>Seleccione</option>
            <option value="Masculino">Masculino</option>
            <option value="Femenino">Femenino</option>
        </select>
        <span asp-validation-for="Apellido" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Actualizar</button>
</form> 

EdgarAguasvivasPrueba/Views/Persona/IndexPersonas.cshtml
@model IEnumerable<EdgarAguasvivasPrueba.Models.Persona>


@{
    Layout = "_Layout";
}



<h3><a asp-action="CreatePersona" class="btn btn-sm btn-secondary">Crear</a></h3>
<table class="table table-bordered table-sm table-striped">
    <thead>
        <tr><th>Id</th><th>Nombre</th><th>Apellido</th><th>Fecha De Nacimiento</th><th>Pasaporte</th><th>Direccion</th><th>Sexo</th><th>...</th></tr>
    </thead>
    <tbody>
        @if (Model == null)
        {
            <tr><td colspan="7" class="text-center">No contiene data</td></tr>

        }
        else
        {
            @foreach (var p in Model)
            {
    <tr>
        <td>@p.Id</td>
        <td>@p.Nombre</td>
        <td>@p.Apellido</td>
        <td>@string.Format("{0:dddd, dd MMMM yyyy}", p.FechaNacimiento)</td>
        <td>@p.Pasaporte</td>
        <td>@p.Direccion</td>
        <td>@p.Sexo</td>
        <td>
            <a asp-action="EditPersona" asp-route-id="@p.Id" class="btn btn-dark">Editar</a>
            <form asp-action="DeletePersona" method="post" asp-route-id="@p.Id">
                <button class="btn btn-danger">Eliminar</button>
            </form>
        </td>
    </tr>

            }
        }
    </tbody>
</table>

EdgarAguasvivasPrueba/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EdgarAguasvivasPrueba</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="" asp-action="">EdgarAguasvivasPrueba</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Solicitudes" asp-action="IndexSolicitudes">Solicitudes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persona" asp-action="IndexPersonas">Personas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EdgarAguasvivasPrueba - <a asp-area="" asp-controller="" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

EdgarAguasvivasPrueba/Views/Solicitudes/CreateSolicitud.cshtml
@model Solicitud

@{
    Layout = "_Layout";
}

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<form class="m-1 p-1" method="post">
    <div class="form-group">
        <label asp-for="Persona"></label>
        <select asp-for="Persona" asp-items="@(@ViewBag.Personas)" class="form-control">
            <option disabled value="0" selected>Seleccione</option>
        </select>
        <span asp-validation-for="Persona" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Estado"></label>       
        <select asp-for="Estado" asp-items="@(ViewBag.Estados)" class="form-control">
            <option disabled value="0" selected>Seleccione</option>
        </select>
        <span asp-validation-for="Estado" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FechaCreacion"></label>
        <input asp-for="FechaCreacion" type="date" class="form-control col-5" />
        <span asp-validation-for="FechaCreacion" class="text-danger"></span>
    </div>
    
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>  

EdgarAguasvivasPrueba/Views/Solicitudes/EditSolicitud.cshtml
@model Solicitud

@{
    Layout = "_Layout";   
}

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<form class="m-1 p-1" method="post">
    <div class="form-group">
        <label asp-for="Id"></label>
        <input asp-for="Id" type="text" readonly class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PersonaId"></label>
        <select asp-for="PersonaId"  asp-items="@(ViewBag.Personas)" class="form-control">           
        </select>
        <span asp-validation-for="Persona" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="EstadoId"></label>
        <select asp-for="EstadoId"  asp-items="@(ViewBag.Estados)" class="form-control">           
        </select>
        <span asp-validation-for="Estado" class="text-danger"></span>
    </div>
    
    <button type="submit" class="btn btn-primary">Actualizar</button>
</form> 

EdgarAguasvivasPrueba/Views/Solicitudes/IndexSolicitudes.cshtml
@model IEnumerable<EdgarAguasvivasPrueba.Models.Solicitud>


@{
    Layout = "_Layout";
}



<h3><a asp-action="CreateSolicitud" class="btn btn-sm btn-secondary">Crear</a></h3>

    <label> Select a status</label>
    <select asp-items="@(@ViewBag.Estados)" class="form-control col-5" id="selectedEstado">
        <option disabled value="0" selected>Seleccione</option>
    </select>
<br />

<table class="table table-bordered table-sm table-striped">
    <thead>
        <tr><th>Id</th><th>Persona</th><th>Estado</th><th>Fecha De Creacion</th><th>...</th></tr>
    </thead>
    <tbody>
        @if (Model == null)
        {
            <tr><td colspan="7" class="text-center">No contiene data</td></tr>

        }
        else
        {
            @foreach (var p in Model)
            {
                <tr>
                    <td>@p.Id</td>
                    <td>@p.Persona.Nombre  @p.Persona.Apellido</td>
                    <td>@p.Estado.EstadoNombre</td>
                    <td>@string.Format("{0:dddd, dd MMMM yyyy}", p.FechaCreacion)</td>
                    <td>
                        <a asp-action="EditSolicitud" asp-route-id="@p.Id" class="btn btn-dark">Editar</a>
                        <form asp-action="DeleteSolicitud" method="post" asp-route-id="@p.Id">
                            <button class="btn btn-danger">Eliminar</button>
                        </form>
                    </td>
                </tr>

            }
        }
    </tbody>
</table>

@section Scripts{
    <script>
        $("#selectedEstado").change(function () {
            $.getJSON('/Solicitudes/IndexSolicitudes', { estado: $("#selectedEstado").val() }, function (company) {
            });
                 })
    </script>

}